OpenClinicaEnvironments:
  ocEnvironments:
     -
         url: http://localhost:8080/OpenClinica-ws
         name: Localhost_8080
         version: 3.6
     -
         url: http://ocdu-openclinica-dev.thehyve.net/OpenClinica-ws
         name: Development Server The Hyve
         version: 3.6
     -
         url: http://ocdu-openclinica-acc.thehyve.net/OpenClinica-ws
         name: Acceptance Server The Hyve
         version: 3.6

