package nl.thehyve.ocdu.models.OcDefinitions;

import nl.thehyve.ocdu.TestUtils;
import nl.thehyve.ocdu.soap.ResponseHandlers.GetStudyMetadataResponseHandler;
import org.apache.commons.lang3.StringUtils;
import org.junit.BeforeClass;
import org.junit.Test;

import javax.xml.soap.MessageFactory;
import javax.xml.soap.SOAPMessage;
import java.io.File;
import java.io.FileInputStream;

import static org.junit.Assert.assertEquals;

/**
 * Tests for the {@link MetaData} class
 * Created by Jacob Rousseau on 28-Jun-2016.
 * Copyright CTMM-TraIT / NKI (c) 2016
 */
public class MetaDataTests {

    private static MetaData metaData;

    @Test
    public void testFindCRFOID() {
        String formOID = metaData.findFormOID("", "0.10");
        assertEquals("", formOID);

        formOID = metaData.findFormOID("", "");
        assertEquals("", formOID);

        formOID = metaData.findFormOID("MUST-FOR_NON_TTP_STUDY", "");
        assertEquals("", formOID);

        formOID = metaData.findFormOID("MUST-FOR_NON_TTP_STUDY", "0.10");
        assertEquals("F_MUSTFOR_NON__010", formOID);
    }

    @Test
    public void testSubjectIDGeneration() throws Exception {
        assertEquals(SubjectIDGeneration.MANUAL_ENTRY, metaData.getSubjectIDGeneration());

        MetaData metaDataAutoGenerated = TestUtils.parseMetaData("docs/responseExamples/metadataAutoGenerated.xml");
        assertEquals(SubjectIDGeneration.AUTOGENERATED_AND_EDITABLE, metaDataAutoGenerated.getSubjectIDGeneration());

        MetaData metaDataAutoGeneratedNonEditable = TestUtils.parseMetaData("docs/responseExamples/metadataAutoGeneratedNonEditable.xml");
        assertEquals(SubjectIDGeneration.AUTOGENERATED_AND_NON_EDITABLE, metaDataAutoGeneratedNonEditable.getSubjectIDGeneration());
    }

    @BeforeClass
    public static void setUp() throws Exception {
        metaData = TestUtils.parseMetaData("docs/responseExamples/getStudyMetadata3.xml");
    }
}
