package nl.thehyve.ocdu.validators.patientDataChecks;

import nl.thehyve.ocdu.models.OCEntities.ClinicalData;
import nl.thehyve.ocdu.models.OCEntities.Subject;
import nl.thehyve.ocdu.models.OcDefinitions.MetaData;
import nl.thehyve.ocdu.models.OcDefinitions.SubjectIDGeneration;
import nl.thehyve.ocdu.models.errors.ErrorClassification;
import nl.thehyve.ocdu.models.errors.ValidationErrorMessage;
import nl.thehyve.ocdu.validators.UtilChecks;
import org.openclinica.ws.beans.StudySubjectWithEventsType;

import java.util.List;
import java.util.Set;

/**
 * Raises a warning that it is not possible to create subjects as specified in the subject's file, because the
 * study is configured to use auto-generated subject ID's.
 * Created by jacob on 10/13/16.
 */
public class AutoGeneratedSubjectIDPatientCheck implements PatientDataCheck {

    @Override
    public ValidationErrorMessage getCorrespondingError(int index, Subject subject, MetaData metaData,
                                                        List<StudySubjectWithEventsType> subjectWithEventsTypes,
                                                        Set<String> ssidsInData, List<String> subjectIDInSubjectInput) {
        if (metaData.getSubjectIDGeneration() == SubjectIDGeneration.MANUAL_ENTRY) {
            return null;
        }
        ValidationErrorMessage error = new ValidationErrorMessage("Study is configured to use auto-generated subject-ID's, subjects will not be created from subjects file.");
        error.setError(true);
        return error;
    }
}
