package nl.thehyve.ocdu.validators;


import nl.thehyve.ocdu.models.OCEntities.ClinicalData;
import nl.thehyve.ocdu.models.OCEntities.Subject;
import nl.thehyve.ocdu.models.OcDefinitions.MetaData;
import nl.thehyve.ocdu.models.errors.ErrorClassification;
import nl.thehyve.ocdu.models.errors.MessageType;
import nl.thehyve.ocdu.models.errors.ValidationErrorMessage;
import nl.thehyve.ocdu.validators.patientDataChecks.*;
import org.openclinica.ws.beans.StudySubjectWithEventsType;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Created by bo on 6/7/16.
 */
public class PatientDataOcChecks {

    private final List<Subject> subjects;
    private final MetaData metadata;
    private final List<StudySubjectWithEventsType> subjEventData;
    private final Set<String> ssidsInData;

    private List<PatientDataCheck> checks = new ArrayList<>();

    public PatientDataOcChecks(MetaData metadata, List<Subject> subjects, List<StudySubjectWithEventsType> subjectWithEventsTypes,
                               Set<String> ssidsInData) {
        this.metadata = metadata;
        this.subjects = subjects;
        this.subjEventData = subjectWithEventsTypes;
        this.ssidsInData = ssidsInData;
        checks.add(new GenderPatientDataCheck());
        checks.add(new DateOfBirthPatientDataCheck());
        checks.add(new PersonIdPatientDataCheck());
        checks.add(new DuplicatePersonIdDataCheck());
        checks.add(new DateOfEnrollmentPatientDataCheck());
        checks.add(new SecondaryIdPatientDataCheck());
        checks.add(new StudyPatientDataCheck());
        checks.add(new SitePatientDataCheck());
        checks.add(new SubjectNotRegistered());
        checks.add(new PresentInData());
        checks.add(new DuplicateSubjectLabelDataCheck());
        checks.add(new AutoGeneratedSubjectIDPatientCheck());
        checks.add(new MissingSiteWarningCheck());
    }

    public List<ValidationErrorMessage> getErrors() {
        List<ValidationErrorMessage> combinedErrors = new ArrayList<>();
        List<String> subjectIDInInputList = subjects.stream().map(Subject::getSsid).collect(Collectors.toList());
        for (PatientDataCheck check : checks) {
            List<ValidationErrorMessage> errors = new ArrayList<>();
            int index = 1;
            for (Subject subject : subjects) {
                ValidationErrorMessage error = check.getCorrespondingError(index, subject, metadata, subjEventData,
                        ssidsInData, subjectIDInInputList);
                if (error != null) {
                    error.setSubject(subject.getSsid());
                    subject.addErrorClassification(ErrorClassification.BLOCK_SUBJECT);
                    errors.add(error);
                }
                index++;
            }
            if (! errors.isEmpty()) {
                String cause = errors.get(0).getMessage();
                ValidationErrorMessage combinedErrorMessage = new ValidationErrorMessage(cause);
                combinedErrorMessage.setMessageType(MessageType.ERROR);
                for (ValidationErrorMessage validationErrorMessage : errors) {
                    combinedErrorMessage.addAllOffendingValues(validationErrorMessage.getOffendingValues());
                }
                combinedErrors.add(combinedErrorMessage);
            }
        }
        return combinedErrors;
    }
}
