/*
 * Copyright © 2016-2017 The Hyve B.V. and Netherlands Cancer Institute (NKI).
 *
 * This file is part of OCDI (OpenClinica Data Importer).
 *
 * OCDI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OCDI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OCDI. If not, see <http://www.gnu.org/licenses/>.
 */

package nl.thehyve.ocdu.validators;


import nl.thehyve.ocdu.models.OCEntities.ClinicalData;
import nl.thehyve.ocdu.models.OCEntities.Subject;
import nl.thehyve.ocdu.models.OcDefinitions.MetaData;
import nl.thehyve.ocdu.models.errors.ErrorClassification;
import nl.thehyve.ocdu.models.errors.MessageType;
import nl.thehyve.ocdu.models.errors.ValidationErrorMessage;
import nl.thehyve.ocdu.validators.patientDataChecks.*;
import org.openclinica.ws.beans.StudySubjectWithEventsType;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Created by bo on 6/7/16.
 */
public class PatientDataOcChecks {

    private final List<Subject> subjects;
    private final MetaData metadata;
    private final List<StudySubjectWithEventsType> subjEventData;
    private final Set<String> ssidsInData;

    private List<PatientDataCheck> checks = new ArrayList<>();

    public PatientDataOcChecks(MetaData metadata, List<Subject> subjects, List<StudySubjectWithEventsType> subjectWithEventsTypes,
                               Set<String> ssidsInData) {
        this.metadata = metadata;
        this.subjects = subjects;
        this.subjEventData = subjectWithEventsTypes;
        this.ssidsInData = ssidsInData;
        checks.add(new GenderPatientDataCheck());
        checks.add(new DateOfBirthPatientDataCheck());
        checks.add(new PersonIdPatientDataCheck());
        checks.add(new PersonIdPresentWarning());
        checks.add(new DuplicatePersonIdDataCheck());
        checks.add(new DateOfEnrollmentPatientDataCheck());
        checks.add(new SecondaryIdPatientDataCheck());
        checks.add(new StudyPatientDataCheck());
        checks.add(new SitePatientDataCheck());
        checks.add(new SubjectNotRegistered());
        checks.add(new PresentInData());
        checks.add(new DuplicateSubjectLabelDataCheck());
        checks.add(new DuplicatePersonIdPatientDataCheck());
        checks.add(new AutoGeneratedSubjectIDPatientCheck());
        checks.add(new MissingSiteWarningCheck());
    }

    public List<ValidationErrorMessage> getErrors() {
        List<ValidationErrorMessage> combinedErrors = new ArrayList<>();
        List<String> subjectIDInInputList = subjects.stream().map(Subject::getSsid).collect(Collectors.toList());
        List<String> personIDInInputList = subjects.stream().map(Subject::getPersonId).collect(Collectors.toList());
        for (PatientDataCheck check : checks) {
            List<ValidationErrorMessage> errors = new ArrayList<>();
            int index = 1;
            for (Subject subject : subjects) {
                ValidationErrorMessage error = check.getCorrespondingError(index, subject, metadata, subjEventData,
                        ssidsInData, subjectIDInInputList, personIDInInputList);
                if (error != null) {
                    error.setSubject(subject.getSsid());
                    if (error.getMessageType() == MessageType.ERROR) {
                        subject.addErrorClassification(ErrorClassification.BLOCK_SUBJECT);
                    }
                    errors.add(error);
                }
                index++;
            }
            if (! errors.isEmpty()) {
                ValidationErrorMessage errorMessage = errors.get(0);
                String cause = errorMessage.getMessage();
                MessageType messageType = errorMessage.getMessageType();
                ValidationErrorMessage combinedErrorMessage = new ValidationErrorMessage(cause);
                combinedErrorMessage.setMessageType(messageType);
                for (ValidationErrorMessage validationErrorMessage : errors) {
                    combinedErrorMessage.addAllOffendingValues(validationErrorMessage.getOffendingValues());
                }
                combinedErrors.add(combinedErrorMessage);
            }
        }
        return combinedErrors;
    }
}
