package nl.thehyve.ocdu.models.OcDefinitions;

/**
 * Created by jacob on 10/13/16.
 */
public enum SubjectIDGeneration {

    MANUAL_ENTRY("manual"),
    AUTOGENERATED_AND_EDITABLE("auto editable"),
    AUTOGENERATED_AND_NON_EDITABLE("auto non-editable");


    private String description;

    SubjectIDGeneration(String description) {
        this.description = description;
    }

    public static SubjectIDGeneration fromString(String value) {
        if (value != null) {
            for (SubjectIDGeneration subjectIDGeneration : SubjectIDGeneration.values()) {
                if (value.equalsIgnoreCase(subjectIDGeneration.description)) {
                    return subjectIDGeneration;
                }
            }
        }
        throw new IllegalStateException("No enumeration present with value: " + value);
    }
}
