/*
 * Copyright © 2016-2017 The Hyve B.V. and Netherlands Cancer Institute (NKI).
 *
 * This file is part of OCDI (OpenClinica Data Importer).
 *
 * OCDI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OCDI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OCDI. If not, see <http://www.gnu.org/licenses/>.
 */

package nl.thehyve.ocdu.models.OcDefinitions;

/**
 * Created by jacob on 10/13/16.
 */
public enum SubjectIDGeneration {

    MANUAL_ENTRY("manual"),
    AUTOGENERATED_AND_EDITABLE("auto editable"),
    AUTOGENERATED_AND_NON_EDITABLE("auto non-editable");


    private String description;

    SubjectIDGeneration(String description) {
        this.description = description;
    }

    public static SubjectIDGeneration fromString(String value) {
        if (value != null) {
            for (SubjectIDGeneration subjectIDGeneration : SubjectIDGeneration.values()) {
                if (value.equalsIgnoreCase(subjectIDGeneration.description)) {
                    return subjectIDGeneration;
                }
            }
        }
        throw new IllegalStateException("No enumeration present with value: " + value);
    }
}
